services:
  frontend:
    build:
      context: ./PaperlessUI/static
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file: docker-compose.env

  api:
    build:
      context: ./PaperlessAPI/out
    restart: unless-stopped
    ports:
      - "8081:8081"
    privileged: true

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./PaperlessDB/local_pgdata:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    user: root
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./PaperlessDB/pgadmin-data:/var/lib/pgadmin



volumes:
  data:
  media:
  pgdata:
  redisdata:
