services:
  frontend:
    container_name: frontend
    build:
      context: ./PaperlessUI/static
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file: docker-compose.env

  api:
    container_name: api
    build:
      context: ./PaperlessAPI
    restart: unless-stopped
    volumes:
      - ./PaperlessAPI/NPaperless.Services/logs:/app/logs
    ports:
      - "8081:8081"
    privileged: true

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./PaperlessDB/local_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  pgadmin:
    image: dpage/pgadmin4
    user: root
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./PaperlessDB/pgadmin-data:/var/lib/pgadmin

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./PaperlessMinIO:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data

  rabbitmq:
    user: root
    container_name: rabbitmq
    image: rabbitmq:3.9.29-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672

  tesseract:
    container_name: tesseract
    build:
      context: ./PaperlessOCR
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq
    volumes:
      - ./PaperlessOCR/images:/mnt/images
      - ./PaperlessOCR/models:/usr/share/tessdata
      - ./PaperlessOCR/config/rabbitmqadmin.config:/etc/rabbitmq/rabbitmqadmin.conf
      - ./PaperlessOCR/script/:/app
      - ./PaperlessOCR/gs-out:/app/gs-out
    ports:
      - 8082:8082
    command: tail -f /dev/null

networks:
  network1:
    name: paperless-network
    

  
