services:
  frontend:
    build:
      context: ./PaperlessUI/static
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file: docker-compose.env

    
  api:
    build:
      context: ./PaperlessAPI/out
    restart: unless-stopped
    ports:
      - "8081:8081"



volumes:
  data:
  media:
  pgdata:
  redisdata:
