CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Correspondents" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    slug text NOT NULL,
    name text NOT NULL,
    match text NOT NULL,
    matching_algorithm bigint NOT NULL,
    is_insensitive boolean NOT NULL,
    document_count bigint NOT NULL,
    last_correspondence timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Correspondents" PRIMARY KEY (id)
);

CREATE TABLE "Documents" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    correspondent bigint NULL,
    "documentType" bigint NULL,
    "storagePath" bigint NULL,
    title text NOT NULL,
    content text NOT NULL,
    tags bigint[] NOT NULL,
    created timestamp with time zone NOT NULL,
    created_date timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    added timestamp with time zone NOT NULL,
    "ArchiveSerialNumber" text NULL,
    "OriginalFileName" text NOT NULL,
    "ArchivedFileName" text NOT NULL,
    CONSTRAINT "PK_Documents" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231127110445_Initial', '7.0.5');

COMMIT;

