CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Correspondents" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    slug text NOT NULL,
    name text NOT NULL,
    match text NOT NULL,
    matching_algorithm bigint NOT NULL,
    is_insensitive boolean NOT NULL,
    document_count bigint NOT NULL,
    last_correspondence timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Correspondents" PRIMARY KEY (id)
);

CREATE TABLE "Documents" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Correspondent" bigint NULL,
    "DocumentType" bigint NULL,
    "StoragePath" bigint NULL,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "Tags" bigint[] NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "Modified" timestamp with time zone NOT NULL,
    "Added" timestamp with time zone NOT NULL,
    "ArchiveSerialNumber" text NULL,
    "OriginalFileName" text NOT NULL,
    "ArchivedFileName" text NOT NULL,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231118221231_Initial', '7.0.13');

COMMIT;

START TRANSACTION;

ALTER TABLE "Documents" RENAME COLUMN "Title" TO title;

ALTER TABLE "Documents" RENAME COLUMN "Tags" TO tags;

ALTER TABLE "Documents" RENAME COLUMN "StoragePath" TO "storagePath";

ALTER TABLE "Documents" RENAME COLUMN "Modified" TO modified;

ALTER TABLE "Documents" RENAME COLUMN "DocumentType" TO "documentType";

ALTER TABLE "Documents" RENAME COLUMN "Created" TO created;

ALTER TABLE "Documents" RENAME COLUMN "Correspondent" TO correspondent;

ALTER TABLE "Documents" RENAME COLUMN "Content" TO content;

ALTER TABLE "Documents" RENAME COLUMN "Added" TO added;

ALTER TABLE "Documents" RENAME COLUMN "Id" TO id;

ALTER TABLE "Documents" RENAME COLUMN "CreatedDate" TO created_date;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231127093436_changed column case', '7.0.13');

COMMIT;

